### ISSUE TITLE
Set the display name of the bot to the web site for transparency

### ISSUE THREAD

**Issue by bkil** [matrix-org/matrix-public-archive#257]
Right now, this should be https://github.com/matrix-org/matrix-public-archive but after #219 is fixed, this could be simply https://archive.matrix.org

It might also be included in the user avatar as well if some platform fails to forward the display name.

The top of the web page and the readme should link to the FAQ that answers something like

> Why did `@archive:matrix.org` join my room?

## Background

Certain communities have a policy about only allowing bots that identify themselves, share their source code and the result of their activities. Some ask that bots respond to `!botlist`, `!rollcall` or if the bot is @-mentioned.

* https://tilde.chat/wiki/bots
* https://rfc.tildeverse.org/rfcs/2

## Alternatives

This could be achieved in multiple ways. The least intrusive of which is to make it trivial to find information about the bot, such as running it under its own subdomain & domain with information about it. The second best is what I suggested above. 

Another possibility is vocally announcing itself after joining, but some may actually find that creepier and more intrusive.

**Comment by MadLittleMods** [comment]
Ideally, we'd have something like [extensible profiles](https://github.com/matrix-org/matrix-spec-proposals/issues/3795) to add a proper explanation and links but that isn't available yet.

The best we can probably do is update the display name. https://github.com/matrix-org/matrix-public-archive/issues/219 will be fixed in any case so we should be thinking of names in that context. Here are some names that have come up:

 - `archive.matrix.org observation assistant`
 - `Read-only user for archive.matrix.org`
 - `Non-archiving user for archive.matrix.org`
 - `Exploratory user for archive.matrix.org`
 - `archive.matrix.org permissions check`

It would be best if the name could preempt assumptions and wrap the kind of [explanation I gave yesterday](https://github.com/matrix-org/matrix-public-archive/issues/47#issuecomment-1568698809).

Having some avatar would be good but ideally would just be the [custom logo](https://github.com/matrix-org/matrix-public-archive/issues/94) of the Matrix Public Archive which doesn't exist yet.

---

I don't think we'd be able serve any bot commands since that would require it's own infrastructure just to answer a rollcall command explaining itself. Something that's really just better served by some profile information anyway.

**Comment by Mikaela** [comment]
> archive.matrix.org observation assistant

I prefer this one as it clearly communicates that it's observing me and my room non-consentually.

**Comment by jonaharagon** [comment]
> Ideally, we'd have something like https://github.com/matrix-org/matrix-spec-proposals/issues/3795 to add a proper explanation and links but that isn't available yet.

Could you just set the display name to `https://archive.matrix.org/bot` or `/faq` or `/about` or whatever, and host a proper explanation on that page?

**Comment by MadLittleMods** [comment]
@jonaharagon Sounds workable. We could just add a redirect from `/faq` to the FAQ on GitHub. PR welcome :fast_forward:

**Comment by MadLittleMods** [comment]
A `/faq` redirect was added in https://github.com/matrix-org/matrix-public-archive/pull/265

And the display name for the `@archive:matrix.org` bot user has been updated to [archive.matrix.org/faq](https://archive.matrix.org/faq)
